on:
  - push
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: zharinov/setup-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: clojure --version
