on:
  - push
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
    
      - uses: zharinov/setup-action@main
        with:
          java: graalvm

      - run: which java
      - run: which native-image
