on:
  - push
  
jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        java-dist:
          - temurin
          - zulu
          - adopt
          - adopt-hotspot
          - adopt-openj9
          - liberica
          - microsoft
          - corretto
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
    
      - uses: zharinov/setup-action@main
        with:
          java: zulu

      - run: java -version
