on:
  - push
  
jobs:
  test:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        java:
          - graalvm
          - temurin
          - zulu
          - adopt
          - adopt-hotspot
          - adopt-openj9
          - liberica
          - microsoft
          - corretto
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
    
      - uses: zharinov/setup-clj@v1.0.2
        with:
          java: ${{ matrix.java }}

      - run: clojure -e "*clojure-version*"
